#!/usr/bin/env bash
# Capture artifact evidence after successful E2E validation
REPO="/mnt/c/IMP/VIT/SY/SEM_2/EDI/NiyamAI-Proj-Code-Original"
cd "$REPO"

echo "=== EVIDENCE COLLECTION ==="

echo ""
echo "--- 1. input.json (feature vector written to disk) ---"
cat input.json

echo ""
echo ""
echo "--- 2. witness.json (generated by ezkl gen-witness) ---"
cat witness.json

echo ""
echo ""
echo "--- 3. proof.json (first 400 chars — full file is 17 KB) ---"
head -c 400 proof.json
echo "..."
echo ""
echo "    [proof.json SHA-256]"
sha256sum proof.json

echo ""
echo "--- 4. Audit DB — last 5 events ---"
python3 -c "
import sys, json
sys.path.insert(0, '.')
from schema.audit_repository import AuditRepository
repo = AuditRepository()
events = repo.fetch_events(limit=5)
for e in events:
    print(json.dumps({
        'event_type': e.get('event_type'),
        'status':     e.get('status'),
        'tool_name':  e.get('tool_name'),
        'verification': e.get('verification'),
        'proof_hash': str(e.get('proof_hash',''))[:32] + '...' if e.get('proof_hash') else None,
        'timestamp':  e.get('timestamp'),
    }, indent=2))
    print()
"

echo ""
echo "--- 5. Audit DB chain integrity ---"
python3 -c "
import sys
sys.path.insert(0, '.')
from schema.audit_repository import AuditRepository
repo = AuditRepository()
chain = repo.verify_chain()
print('valid         :', chain['valid'])
print('events_checked:', chain['events_checked'])
print('broken_links  :', chain['broken_links'])
if chain['anomalies']:
    print('anomalies     :', chain['anomalies'][:3])
else:
    print('anomalies     : none')
"

echo ""
echo "=== EVIDENCE COLLECTION COMPLETE ==="
